### ISSUE TITLE
Application crashing (Route) if GPS enable popup is ignored

### ISSUE THREAD

**Issue by abhishekzambre** [abhishekzambre/mc_group_10#3]
Getting below exception.

E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: mcgroup10.com.batroid, PID: 29097
                  android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@3380d31e is not valid; is your activity running?
                      at android.view.ViewRootImpl.setView(ViewRootImpl.java:673)
                      at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:301)
                      at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
                      at android.app.Dialog.show(Dialog.java:337)
                      at mcgroup10.com.batroid.RouteMap.showDialogGPS(RouteMap.java:344)
                      at mcgroup10.com.batroid.RouteMap.access$000(RouteMap.java:54)
                      at mcgroup10.com.batroid.RouteMap$1.run(RouteMap.java:295)
                      at android.os.Handler.handleCallback(Handler.java:739)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:159)
                      at android.app.ActivityThread.main(ActivityThread.java:5541)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:372)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
I/Process: Sending signal. PID: 29097 SIG: 9

**Comment by abhishekzambre** [comment]
Steps to reproduce->
1. Click "Route".
2. Click "Ignore" on GPS enable popup.
3. Come back to main activity.
4. Wait for it.

**Comment by abhishekzambre** [comment]
Issue fixed by #4
