### ISSUE TITLE
Application crashing when clicked on Birthdays or Auto-Reply

### ISSUE THREAD

**Issue by abhishekzambre** [abhishekzambre/mc_group_10#8]
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: mcgroup10.com.batroid, PID: 13533
                  java.lang.NoSuchMethodError: No virtual method checkSelfPermission(Ljava/lang/String;)I in class Lmcgroup10/com/batroid/Birthdays; or its super classes (declaration of 'mcgroup10.com.batroid.Birthdays' appears in /data/data/mcgroup10.com.batroid/files/instant-run/dex/slice-slice_3-classes.dex)
                      at mcgroup10.com.batroid.Birthdays.addPermission(Birthdays.java:126)
                      at mcgroup10.com.batroid.Birthdays.checkReceivePermission(Birthdays.java:84)
                      at mcgroup10.com.batroid.Birthdays.onCreate(Birthdays.java:58)
                      at android.app.Activity.performCreate(Activity.java:6093)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2458)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2577)
                      at android.app.ActivityThread.access$1000(ActivityThread.java:164)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1462)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:159)
                      at android.app.ActivityThread.main(ActivityThread.java:5541)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:372)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:964)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:759)
V/Process: killProcess [13533] Callers=com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException:99 java.lang.ThreadGroup.uncaughtException:693 java.lang.ThreadGroup.uncaughtException:690 <bottom of call stack> 
I/Process: Sending signal. PID: 13533 SIG: 9
Application terminated.

**Comment by abhishekzambre** [comment]
@murlee417 is it still valid?

**Comment by murlee417** [comment]
@abhishekzambre `my` mobile runs marshmallow update because of that I am not seeing this problem.

**Comment by abhishekzambre** [comment]
@murlee417 ok, is it possible to put this block in try-catch, so application won't crash? If too much efforts, lets ignore this.

**Comment by murlee417** [comment]
From marshmallow update onwards, programmer has to handle user permission in java code. so I have written 2-3 functions to check permission, if not grant permission, handle never ask again check box, all these.
Actually no idea where to put try block. Can we ignore this?

**Comment by murlee417** [comment]
@abhishekzambre ^^

**Comment by abhishekzambre** [comment]
@murlee417 , will see if I can find anything, else we'll ignore.

**Comment by murlee417** [comment]
@abhishekzambre okay
